"""add_family_member_permissions_columns

Revision ID: e996d56b33b3
Revises: 53751257f1ae
Create Date: 2026-03-29 21:46:48.316709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e996d56b33b3'
down_revision: Union[str, Sequence[str], None] = '53751257f1ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # --- accounts ---
    op.add_column('accounts', sa.Column('credit_limit', sa.Integer(), nullable=True))
    op.add_column('accounts', sa.Column('low_balance_alert', sa.Integer(), nullable=True))
    op.execute("CREATE TYPE account_usage_type AS ENUM ('PERSONAL','SALARY','SAVINGS','BUSINESS','INVESTMENT','JOINT')")
    op.add_column('accounts', sa.Column('usage_type', postgresql.ENUM('PERSONAL', 'SALARY', 'SAVINGS', 'BUSINESS', 'INVESTMENT', 'JOINT', name='account_usage_type', create_type=False), nullable=True))

    # --- budgets ---
    op.add_column('budgets', sa.Column('alert_threshold', sa.SmallInteger(), nullable=True))
    op.execute("UPDATE budgets SET alert_threshold = 80 WHERE alert_threshold IS NULL")
    op.alter_column('budgets', 'alert_threshold', nullable=False)
    op.add_column('budgets', sa.Column('alert_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False))

    # --- debts ---
    op.execute("CREATE TYPE debt_nature AS ENUM ('FORMAL','INFORMAL')")
    op.add_column('debts', sa.Column('nature', postgresql.ENUM('FORMAL', 'INFORMAL', name='debt_nature', create_type=False), nullable=True))
    op.execute("UPDATE debts SET nature = 'FORMAL' WHERE nature IS NULL")
    op.alter_column('debts', 'nature', nullable=False)
    op.execute("CREATE TYPE creditor_type AS ENUM ('BANK','FINANCIAL','FAMILY','FRIENDS','SUPPLIER','EMPLOYER','OTHER')")
    op.add_column('debts', sa.Column('creditor_type', postgresql.ENUM('BANK', 'FINANCIAL', 'FAMILY', 'FRIENDS', 'SUPPLIER', 'EMPLOYER', 'OTHER', name='creditor_type', create_type=False), nullable=True))
    op.add_column('debts', sa.Column('linked_account_id', sa.UUID(), nullable=True))
    op.add_column('debts', sa.Column('auto_pay_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('debts', sa.Column('is_paid_off', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('debts', sa.Column('paid_off_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key('fk_debts_linked_account', 'debts', 'accounts', ['linked_account_id'], ['id'], ondelete='SET NULL')

    # --- families ---
    op.execute("UPDATE families SET currency = 'AOA' WHERE currency IS NULL")
    op.alter_column('families', 'currency',
               existing_type=postgresql.ENUM('AOA', 'USD', 'EUR', 'MZN', 'CVE', name='currency_code'),
               nullable=False,
               existing_server_default=sa.text("'AOA'::currency_code"))
    op.execute("UPDATE families SET month_start_day = 1 WHERE month_start_day IS NULL")
    op.alter_column('families', 'month_start_day',
               existing_type=sa.SMALLINT(),
               nullable=False,
               existing_server_default=sa.text('1'))

    # --- goals ---
    op.add_column('goals', sa.Column('savings_account_id', sa.UUID(), nullable=True))
    op.add_column('goals', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('goals', sa.Column('image_url', sa.Text(), nullable=True))
    op.execute("UPDATE goals SET contribution_frequency = 'MONTHLY' WHERE contribution_frequency IS NULL")
    op.alter_column('goals', 'contribution_frequency',
               existing_type=postgresql.ENUM('WEEKLY', 'BIWEEKLY', 'MONTHLY', 'QUARTERLY', 'SEMIANNUAL', 'YEARLY', name='recurrence_frequency'),
               nullable=False,
               existing_server_default=sa.text("'MONTHLY'::recurrence_frequency"))
    op.create_foreign_key('fk_goals_savings_account', 'goals', 'accounts', ['savings_account_id'], ['id'], ondelete='SET NULL')
    op.drop_column('goals', 'monthly_contribution')

    # --- transactions ---
    op.add_column('transactions', sa.Column('attachments', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False))
    op.add_column('transactions', sa.Column('to_account_id', sa.UUID(), nullable=True))
    op.create_foreign_key('fk_transactions_to_account', 'transactions', 'accounts', ['to_account_id'], ['id'])
    op.drop_column('transactions', 'receipt_url')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('receipt_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'to_account_id')
    op.drop_column('transactions', 'attachments')
    op.add_column('goals', sa.Column('monthly_contribution', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'goals', type_='foreignkey')
    op.alter_column('goals', 'contribution_frequency',
               existing_type=postgresql.ENUM('WEEKLY', 'BIWEEKLY', 'MONTHLY', 'QUARTERLY', 'SEMIANNUAL', 'YEARLY', name='recurrence_frequency'),
               nullable=True,
               existing_server_default=sa.text("'MONTHLY'::recurrence_frequency"))
    op.drop_column('goals', 'image_url')
    op.drop_column('goals', 'description')
    op.drop_column('goals', 'savings_account_id')
    op.alter_column('families', 'month_start_day',
               existing_type=sa.SMALLINT(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('families', 'currency',
               existing_type=postgresql.ENUM('AOA', 'USD', 'EUR', 'MZN', 'CVE', name='currency_code'),
               nullable=True,
               existing_server_default=sa.text("'AOA'::currency_code"))
    op.drop_constraint(None, 'debts', type_='foreignkey')
    op.drop_column('debts', 'paid_off_at')
    op.drop_column('debts', 'is_paid_off')
    op.drop_column('debts', 'auto_pay_enabled')
    op.drop_column('debts', 'linked_account_id')
    op.drop_column('debts', 'creditor_type')
    op.drop_column('debts', 'nature')
    op.drop_column('budgets', 'alert_enabled')
    op.drop_column('budgets', 'alert_threshold')
    op.drop_column('accounts', 'usage_type')
    op.drop_column('accounts', 'low_balance_alert')
    op.drop_column('accounts', 'credit_limit')
    # ### end Alembic commands ###
